-- Placeholder reviews so the map has ratings to browse and test.

insert into reviews (id, bathroom_id, rating, cleanliness, availability, accessibility, atmosphere, access_type, critique, reviewer_name, created_at) values
  -- Gun Barrel City, extra depth
  ('rev-gbc-walmart-3', 'seed-gbc-walmart', 5, 5, 5, 5, 4, 'customers', 'Went at 9am. Two family stalls, soap full, floors dry. Best grocery restroom on 198.', 'Sunday shopper', now() - interval '3 hours'),
  ('rev-gbc-chilis-2', 'seed-gbc-chilis', 3, 3, 4, 4, 3, 'customers', 'Fine if you order something. Paper towels were out at lunch. Stall lock works.', 'Lake regular', now() - interval '2 days'),
  ('rev-gbc-mcd-2', 'seed-gbc-mcdonalds', 3, 3, 5, 3, 2, 'customers', 'Busy after school. Code still on the receipt. Grab a napkin on the way in just in case.', 'Mabank commuter', now() - interval '9 hours'),
  ('rev-gbc-lowes-2', 'seed-gbc-lowes', 4, 4, 4, 5, 4, 'customers', 'Quiet even on Saturday. Wide stall, automatic faucet. Closes at store close.', 'Weekend project', now() - interval '18 hours'),
  ('rev-gbc-huddle-1', 'seed-gbc-huddle', 4, 4, 4, 3, 4, 'customers', 'Ask at the counter. Smells like coffee, not cleaner. Perfectly fine with a Grand Slam.', 'Early bird', now() - interval '11 hours'),
  ('rev-gbc-huddle-2', 'seed-gbc-huddle', 3, 3, 5, 3, 3, 'customers', 'Open when everything else is closed. Single stall. They do not mind if you bought coffee.', 'Night shift', now() - interval '4 days'),
  ('rev-gbc-murphy-1', 'seed-gbc-murphy', 3, 3, 5, 3, 2, 'customers', 'Next to Walmart. Key from the clerk. Better than the Exxon, worse than the Supercenter.', 'Boat trailer', now() - interval '7 hours'),
  ('rev-gbc-murphy-2', 'seed-gbc-murphy', 2, 2, 4, 2, 2, 'customers', 'Floor was sticky after the weekend. Use it if you are already pumping.', 'Verified local', now() - interval '6 days'),
  ('rev-gbc-exxon-2', 'seed-gbc-exxon', 3, 3, 4, 2, 2, 'customers', 'Improved since last month. Still ask inside. Soap was actually there today.', 'Lake regular', now() - interval '20 hours'),
  ('rev-gbc-chevron-1', 'seed-gbc-chevron', 3, 3, 4, 3, 3, 'customers', 'Door code on the pump receipt. Average highway stop. Lights work, lock works.', 'Mabank commuter', now() - interval '15 hours'),
  ('rev-gbc-chevron-2', 'seed-gbc-chevron', 4, 4, 4, 3, 3, 'customers', 'Cleaner than I expected at 7am. Paper towels stocked. Quick in and out.', 'Early bird', now() - interval '2 days'),
  ('rev-gbc-park-2', 'seed-gbc-park', 4, 4, 3, 3, 4, 'public', 'Opened after mowing. Smelled like pine cleaner. Best public option in town if you time it.', 'Ballgame parent', now() - interval '30 hours'),
  ('rev-gbc-park-3', 'seed-gbc-park', 2, 2, 4, 2, 2, 'public', 'Saturday tournament crush. One stall, no soap. Walk to City Hall if you can.', 'Verified local', now() - interval '5 days'),
  ('rev-gbc-bk-1', 'seed-gbc-bk', 4, 4, 5, 4, 3, 'customers', 'Code on the receipt. Bright, stocked, and the stall is bigger than it looks from the hall.', 'Sunday shopper', now() - interval '8 hours'),
  ('rev-gbc-bk-2', 'seed-gbc-bk', 3, 3, 5, 4, 3, 'customers', 'Lunch rush line for the restroom too. Still better than the gas stations.', 'Lake regular', now() - interval '3 days'),
  ('rev-gbc-whataburger-2', 'seed-gbc-whataburger', 5, 5, 5, 4, 4, 'customers', '2am stop after the lake. Spotless, lock worked, soap full. Keep this one bookmarked.', 'Night shift', now() - interval '1 day'),
  ('rev-gbc-whataburger-3', 'seed-gbc-whataburger', 3, 3, 5, 4, 3, 'customers', 'Dinner rush. Floors damp but usable. Honey butter chicken sandwich as cover.', 'Verified local', now() - interval '4 days'),
  ('rev-gbc-dq-1', 'seed-gbc-dq', 4, 4, 4, 3, 4, 'customers', 'Ask at the window if the lobby is slow. Clean enough, smells like waffle cone. No complaints.', 'Blizzard run', now() - interval '12 hours'),
  ('rev-gbc-dq-2', 'seed-gbc-dq', 3, 3, 3, 3, 3, 'customers', 'Single stall. Fine with a cone. They lock it after lobby hours.', 'Lake regular', now() - interval '6 days'),
  ('rev-gbc-sonic-1', 'seed-gbc-sonic', 2, 2, 3, 2, 2, 'customers', 'Ask a carhop. Tight, not accessible, and not always open. Last resort on the lane.', 'Mabank commuter', now() - interval '16 hours'),
  ('rev-gbc-sonic-2', 'seed-gbc-sonic', 3, 3, 3, 2, 3, 'customers', 'Better in the morning. They will point you to the door if you ordered a drink.', 'Early bird', now() - interval '2 days'),
  ('rev-gbc-dollar-1', 'seed-gbc-dollar-gen', 3, 3, 4, 3, 2, 'customers', 'Back left. Ask if the light is off. Functional, no frills, and they do not mind shoppers.', 'Sunday shopper', now() - interval '22 hours'),
  ('rev-gbc-cvs-1', 'seed-gbc-cvs', 4, 4, 4, 4, 3, 'customers', 'Ask pharmacy. Clean, quiet, and usually empty. Closes with the store.', 'Verified local', now() - interval '10 hours'),
  ('rev-gbc-cvs-2', 'seed-gbc-cvs', 5, 5, 3, 5, 4, 'customers', 'Accessible stall, automatic everything. My preferred stop west of Main.', 'Weekend project', now() - interval '3 days'),
  ('rev-gbc-subway-1', 'seed-gbc-subway', 3, 3, 4, 3, 3, 'customers', 'Key from the counter. Small but stocked. Buy a cookie and you are golden.', 'Lake regular', now() - interval '5 hours'),
  ('rev-gbc-pizza-1', 'seed-gbc-pizzahut', 4, 4, 3, 3, 3, 'customers', 'Hall by the buffet. Cleaner than the dining room at lunch. They keep it locked after 9.', 'Ballgame parent', now() - interval '1 day'),
  ('rev-gbc-autozone-1', 'seed-gbc-autozone', 3, 3, 3, 3, 2, 'customers', 'Ask at the counter. One stall, industrial soap, no line. Closes with the store.', 'Weekend project', now() - interval '14 hours'),
  ('rev-gbc-family-1', 'seed-gbc-family-dollar', 2, 2, 3, 2, 2, 'customers', 'Staff has to unlock it. Bring your own tissue. Dollar General next door is better.', 'Verified local', now() - interval '4 days'),
  ('rev-gbc-mainbar-1', 'seed-gbc-mainstreet-bar', 3, 3, 4, 3, 4, 'customers', 'Busy on karaoke night. Soap was there, lock was there, lighting is bar lighting.', 'Lake regular', now() - interval '9 hours'),
  ('rev-gbc-mainbar-2', 'seed-gbc-mainstreet-bar', 4, 4, 4, 3, 4, 'customers', 'Weeknight was calm. Cleaner than expected for a sports bar. Order a tea and go.', 'Night shift', now() - interval '6 days'),
  ('rev-gbc-elagave-1', 'seed-gbc-elagave', 4, 4, 4, 3, 5, 'customers', 'Nice tile, good lighting, salsa music from the hall. Customers only and worth the chips.', 'Sunday shopper', now() - interval '7 hours'),
  ('rev-gbc-elagave-2', 'seed-gbc-elagave', 5, 5, 3, 4, 5, 'customers', 'Best atmosphere on east Main. Single stall, actually private. Go during dinner, not close.', 'Verified local', now() - interval '2 days'),
  ('rev-gbc-whiskey-1', 'seed-gbc-whiskey', 3, 3, 4, 2, 4, 'customers', 'Classic bar restroom. Fine if you bought a burger. Not accessible, not fancy, gets the job done.', 'Boat trailer', now() - interval '19 hours'),
  ('rev-gbc-little-1', 'seed-gbc-littlemexico', 3, 3, 3, 2, 3, 'customers', 'Small, toward the back. They are kind about it if you ordered. Not wheelchair friendly.', 'Mabank commuter', now() - interval '13 hours'),
  ('rev-gbc-cochrans-1', 'seed-gbc-cochrans', 4, 4, 4, 4, 4, 'customers', 'Cafeteria restroom: wide, stocked, no rush. Open with lunch hours. A sleeper hit.', 'Early bird', now() - interval '1 day'),
  ('rev-gbc-milanos-1', 'seed-gbc-milanos', 3, 3, 3, 3, 3, 'customers', 'One stall by the register hallway. Fine with a slice. Ask if the light is off.', 'Ballgame parent', now() - interval '28 hours'),
  ('rev-gbc-cefco-1', 'seed-gbc-cefco', 4, 4, 5, 4, 3, 'customers', '24 hours and actually cleaned. Better than most highway stores. Coffee as cover.', 'Night shift', now() - interval '6 hours'),
  ('rev-gbc-cefco-2', 'seed-gbc-cefco', 3, 3, 5, 4, 3, 'customers', 'Busy when the lake empties on Sunday. Still beats the Sunoco on the east side.', 'Boat trailer', now() - interval '3 days'),
  ('rev-gbc-sunoco-1', 'seed-gbc-sunoco', 2, 2, 4, 2, 2, 'customers', 'Ask inside. Dim, and the lock sticks. Use CEFCO or Walmart if you can keep driving.', 'Lake regular', now() - interval '17 hours'),
  ('rev-gbc-brook-1', 'seed-gbc-brookshires', 4, 4, 4, 5, 3, 'customers', 'Back of store, grocery side. Clean, accessible, and quieter than Walmart on Saturday.', 'Mabank commuter', now() - interval '8 hours'),
  ('rev-gbc-brook-2', 'seed-gbc-brookshires', 5, 5, 4, 5, 4, 'customers', 'Spotless after 10am restock. Family stall. My Mabank default.', 'Sunday shopper', now() - interval '5 days'),
  ('rev-gbc-tractor-1', 'seed-gbc-tractor', 4, 4, 4, 4, 3, 'customers', 'Front of store to the left. Ranch-store clean. Closes with the doors.', 'Weekend project', now() - interval '21 hours'),
  ('rev-gbc-cityhall-1', 'seed-gbc-cityhall', 5, 5, 3, 5, 4, 'public', 'Open during city hours. Quiet, accessible, and actually maintained. Do not count on it at night.', 'Verified local', now() - interval '2 days'),
  ('rev-gbc-cityhall-2', 'seed-gbc-cityhall', 4, 4, 2, 5, 4, 'public', 'Best public restroom in town if you hit weekday hours. Locked after close, obviously.', 'Early bird', now() - interval '6 days'),
  ('rev-purtis-1', 'seed-purtis', 4, 4, 4, 4, 4, 'public', 'Park headquarters area. Cleaner than the lake parks. Day-use hours. Worth the drive if you are already camping.', 'Boat trailer', now() - interval '1 day'),
  ('rev-purtis-2', 'seed-purtis', 3, 3, 3, 3, 4, 'public', 'Trailhead vault style at the far lot. Headquarters building is the one you want.', 'Weekend project', now() - interval '4 days'),

  -- San Francisco extras for city hops
  ('rev-tartine-2', 'seed-tartine', 3, 3, 2, 3, 4, 'customers', 'Need a pastry as cover and the line is the line. Clean enough once you get there.', 'Mission walker', now() - interval '16 hours'),
  ('rev-innout-2', 'seed-in-n-out', 5, 5, 5, 4, 3, 'customers', 'Wharf location, late hours, receipt code. Bright and stocked. Tourist-proof.', 'Night shift', now() - interval '3 hours'),
  ('rev-zaf-1', 'seed-zaf', 4, 4, 3, 3, 5, 'customers', 'Ask the host. Nice tile, low light, customers only. A Folsom rescue if you are dining.', 'Verified local', now() - interval '2 days'),
  ('rev-shell-1', 'seed-shell-market', 2, 2, 4, 2, 2, 'customers', 'Key on a plank. Emergency only. Walk to Salesforce Park if you can spare four minutes.', 'Downtown rider', now() - interval '11 hours'),
  ('rev-wf-1', 'seed-whole-foods', 5, 5, 4, 5, 4, 'customers', 'Downstairs near the checkout. Spotless, accessible, and they do not fuss.', 'Verified local', now() - interval '7 hours'),
  ('rev-wf-2', 'seed-whole-foods', 4, 4, 4, 5, 4, 'customers', 'Busy at lunch. Still the best grocery restroom south of Market.', 'Mission walker', now() - interval '3 days'),
  ('rev-safeway-1', 'seed-safeway-marina', 4, 4, 4, 4, 3, 'customers', 'Back of store. Marina standard: clean, fluorescent, reliable.', 'Early bird', now() - interval '20 hours'),
  ('rev-alta-1', 'seed-alta-plaza', 3, 3, 3, 3, 4, 'public', 'Park restroom by the tennis courts. Morning is best. Bring a backup tissue after 3pm.', 'Pacific Heights dog', now() - interval '1 day'),
  ('rev-westfield-1', 'seed-westfield', 4, 4, 4, 5, 3, 'customers', 'Fourth floor near the food court. Mall clean, always a wait at noon.', 'Downtown rider', now() - interval '9 hours'),
  ('rev-ferry-2', 'seed-ferry-building', 4, 4, 4, 4, 4, 'public', 'Downstairs near the bay side. Saturday market crush, weekday calm.', 'Verified local', now() - interval '6 hours'),
  ('rev-nyc-shake-1', 'seed-nyc-shake', 4, 4, 3, 3, 4, 'customers', 'Ask at the counter. Tight but clean. Madison Square Park restroom next door is public if the line is long.', 'Union Square lunch', now() - interval '14 hours'),
  ('rev-nyc-wf-1', 'seed-nyc-wholefoods', 5, 5, 4, 5, 4, 'customers', 'Lower level. Quiet, stocked, and actually private. Best grocery stop in Union Square.', 'Verified local', now() - interval '2 days'),
  ('rev-chi-g-1', 'seed-chi-giordano', 3, 3, 3, 3, 4, 'customers', 'Down the hall. Fine with a slice. Loop lunch crowds, not a destination.', 'Loop walker', now() - interval '18 hours')
on conflict (id) do nothing;
